# .github/workflows/release.yml
name: Build & Attach Windows Release

on:
  push:
    tags: ['v*']   # runs when you push tags like v2.0.3

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write   # needed to create/upload the release asset

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'   # if this image lacks 3.13, change to '3.12'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: py -m PyInstaller ".\Breakers Companion.spec"

      - name: Package zip
        shell: pwsh
        run: |
          $ver = "${{ github.ref_name }}"           # e.g. v2.0.3
          $pkg = "Breakers Companion-$ver"
          New-Item -ItemType Directory $pkg | Out-Null
          Copy-Item ".\dist\Breakers Companion.exe" "$pkg\Breakers Companion.exe"
          Copy-Item -Recurse ".\assets" "$pkg\assets"
          Compress-Archive -Path "$pkg\*" -DestinationPath "$pkg.zip" -Force
          "PKG_ZIP=$pkg.zip" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: ${{ env.PKG_ZIP }}

      - name: Attach zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PKG_ZIP }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
